rate: 10 
controller_list:
  - name: fake_arm_19_controller
    type: interpolate | via points | last point
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6

gains: # Required because we're controlling an effort interface
    joint1: {p: 100,  d: 10, i: 0.01, i_clamp: 1}
    joint2: {p: 100,  d: 10, i: 0.01, i_clamp: 1}
    joint3: {p: 100,  d: 10, i: 0.01, i_clamp: 1}
    joint4: {p: 100,  d: 10, i: 0.01, i_clamp: 1}
    joint5: {p: 100,  d: 10, i: 0.01, i_clamp: 1}
    joint6: {p: 100,  d: 10, i: 0.01, i_clamp: 1}

constraints:
    joint1:
      goal: 0.1
    joint2:
      goal: 0.1
    joint3:
      goal: 0.1
    joint4:
      goal: 0.1
    joint5:
      goal: 0.1
    joint6:
      goal: 0.1
    goal_time: 100
